defmodule SuchConfigDesktop.ProjectVault.AiIgnoreTemplates do
  @moduledoc false

  @baseline """
  # Secrets & credentials
  .env
  .env.*
  !.env.example
  !.env.*.example
  **/*.pem
  **/*.key
  **/id_rsa
  **/id_ed25519
  **/credentials.json
  **/secrets.json
  **/.secrets
  **/secrets/
  **/*.suchvault

  # Dependencies & build
  node_modules/
  **/node_modules/
  dist/
  build/
  __pycache__/
  _build/
  deps/
  target/
  **/target/

  # Local Broker / SuchConfig runtime
  broker.sock
  **/*.sock
  .suchconfig/
  *.manifest.json

  # Logs & OS
  *.log
  .DS_Store
  .idea/
  .vscode/
  *.swp
  *.swo
  *~
  """

  @known_paths [
    ".cursorignore",
    ".claudeignore",
    ".windsurfignore",
    ".aiderignore",
    ".kiroignore"
  ]

  def known_paths, do: @known_paths

  def content_for(path) when path in @known_paths do
    header = "# Generated by SuchConfig Project Vault — secrets-safe AI ignore baseline\n\n"
    {:ok, header <> @baseline}
  end

  def content_for(_), do: {:error, :unknown_template}

  def write_if_missing(root_path, relative_path)
      when is_binary(root_path) and is_binary(relative_path) do
    root = String.trim(root_path)
    rel = String.trim(relative_path)

    cond do
      root == "" or not File.dir?(root) ->
        {:error, :invalid_root}

      rel == "" or String.contains?(rel, "/") or String.contains?(rel, "\\") ->
        {:error, :invalid_path}

      rel not in @known_paths ->
        {:error, :unknown_template}

      true ->
        abs = Path.join(root, rel)

        if File.exists?(abs) do
          {:skipped, :exists}
        else
          case content_for(rel) do
            {:ok, body} ->
              case File.write(abs, body) do
                :ok -> :ok
                {:error, reason} -> {:error, reason}
              end

            other ->
              other
          end
        end
    end
  end

  def write_if_missing(_, _), do: {:error, :invalid_args}
end
