defmodule SuchConfigDesktop.ProjectVault.AiIgnoreTemplates do
  @moduledoc false

  @known_paths [
    ".cursorignore",
    ".claudeignore",
    ".windsurfignore",
    ".aiderignore",
    ".kiroignore"
  ]

  @secrets [
    ".env",
    ".env.*",
    "!.env.example",
    "!.env.*.example",
    "**/*.pem",
    "**/*.key",
    "**/id_rsa",
    "**/id_ed25519",
    "**/credentials.json",
    "**/secrets.json",
    "**/.secrets",
    "**/secrets/",
    "**/*.suchvault"
  ]

  @suchconfig_runtime [
    "broker.sock",
    "**/*.sock",
    ".suchconfig/",
    "*.manifest.json"
  ]

  @logs_os [
    "*.log",
    ".DS_Store",
    ".idea/",
    ".vscode/",
    "*.swp",
    "*.swo",
    "*~"
  ]

  @stack_build %{
    node: ["node_modules/", "**/node_modules/", "dist/", "build/"],
    python: ["__pycache__/"],
    elixir: ["_build/", "deps/"],
    rust: ["target/", "**/target/"]
  }

  @manifest_signals [
    {"package.json", :node},
    {"pnpm-lock.yaml", :node},
    {"package-lock.json", :node},
    {"yarn.lock", :node},
    {"bun.lockb", :node},
    {"mix.exs", :elixir},
    {"Cargo.toml", :rust},
    {"pyproject.toml", :python},
    {"requirements.txt", :python},
    {"Pipfile", :python},
    {"setup.py", :python},
    {"setup.cfg", :python}
  ]

  @gitignore_stack_hints [
    {~r/(^|\/|\*\*\/)node_modules\/?$/, :node},
    {~r/(^|\/)dist\/?$/, :node},
    {~r/(^|\/)build\/?$/, :node},
    {~r/(^|\/)__pycache__\/?$/, :python},
    {~r/(^|\/)_build\/?$/, :elixir},
    {~r/(^|\/)deps\/?$/, :elixir},
    {~r/(^|\/|\*\*\/)target\/?$/, :rust}
  ]

  @merge_skip_exact MapSet.new(
                      @secrets ++
                        List.flatten(Map.values(@stack_build)) ++
                        @suchconfig_runtime ++ @logs_os,
                      &{&1, true}
                    )

  def known_paths, do: @known_paths

  def content_for(path) when path in @known_paths do
    {:ok, render_body(detect_context(nil))}
  end

  def content_for(path, root_path) when path in @known_paths and is_binary(root_path) do
    {:ok, render_body(detect_context(root_path))}
  end

  def content_for(path, _) when path in @known_paths do
    content_for(path)
  end

  def content_for(_, _), do: {:error, :unknown_template}

  def write_if_missing(root_path, relative_path)
      when is_binary(root_path) and is_binary(relative_path) do
    root = String.trim(root_path)
    rel = String.trim(relative_path)

    cond do
      root == "" or not File.dir?(root) ->
        {:error, :invalid_root}

      rel == "" or String.contains?(rel, "/") or String.contains?(rel, "\\") ->
        {:error, :invalid_path}

      rel not in @known_paths ->
        {:error, :unknown_template}

      true ->
        abs = Path.join(root, rel)

        if File.exists?(abs) do
          {:skipped, :exists}
        else
          case content_for(rel, root) do
            {:ok, body} ->
              case File.write(abs, body) do
                :ok -> :ok
                {:error, reason} -> {:error, reason}
              end

            other ->
              other
          end
        end
    end
  end

  def write_if_missing(_, _), do: {:error, :invalid_args}

  defp render_body(%{stacks: stacks, from_gitignore: extras, used_gitignore?: used?}) do
    header =
      if used? do
        "# Generated by SuchConfig Project Vault — secrets-safe AI ignore baseline (tightened from .gitignore)\n\n"
      else
        "# Generated by SuchConfig Project Vault — secrets-safe AI ignore baseline\n\n"
      end

    build_lines =
      stacks |> Enum.sort() |> Enum.flat_map(&Map.fetch!(@stack_build, &1)) |> Enum.uniq()

    sections = [
      {"# Secrets & credentials", @secrets},
      {"# Dependencies & build", build_lines},
      {"# Local Broker / SuchConfig runtime", @suchconfig_runtime},
      {"# Logs & OS", @logs_os}
    ]

    sections =
      if extras == [] do
        sections
      else
        sections ++ [{"# From project .gitignore", extras}]
      end

    body =
      sections
      |> Enum.map(fn {title, lines} -> title <> "\n" <> Enum.join(lines, "\n") end)
      |> Enum.join("\n\n")

    header <> body <> "\n"
  end

  defp detect_context(nil) do
    %{stacks: Map.keys(@stack_build), from_gitignore: [], used_gitignore?: false}
  end

  defp detect_context(root) do
    root = String.trim(root)
    gitignore_path = Path.join(root, ".gitignore")
    gitignore_patterns = read_gitignore_patterns(gitignore_path)
    used_gitignore? = gitignore_patterns != []

    stacks =
      detect_stacks(root, gitignore_patterns)
      |> case do
        [] -> Map.keys(@stack_build)
        found -> found
      end

    covered =
      stacks
      |> Enum.flat_map(&Map.fetch!(@stack_build, &1))
      |> Kernel.++(@secrets)
      |> Kernel.++(@suchconfig_runtime)
      |> Kernel.++(@logs_os)
      |> MapSet.new()

    extras =
      gitignore_patterns
      |> Enum.reject(&MapSet.member?(covered, &1))
      |> Enum.reject(&Map.has_key?(@merge_skip_exact, &1))
      |> Enum.reject(&redundant_pattern?(&1, covered))
      |> Enum.uniq()
      |> Enum.sort()
      |> Enum.take(80)

    %{stacks: stacks, from_gitignore: extras, used_gitignore?: used_gitignore?}
  end

  defp detect_stacks(root, gitignore_patterns) do
    from_manifests =
      for {file, stack} <- @manifest_signals,
          File.regular?(Path.join(root, file)),
          do: stack

    from_gitignore =
      for pattern <- gitignore_patterns,
          {rx, stack} <- @gitignore_stack_hints,
          Regex.match?(rx, pattern),
          do: stack

    (from_manifests ++ from_gitignore)
    |> Enum.uniq()
  end

  defp read_gitignore_patterns(gitignore_path) do
    case File.read(gitignore_path) do
      {:ok, bin} ->
        bin
        |> String.split(~r/\r\n|\n|\r/)
        |> Enum.map(&String.trim/1)
        |> Enum.reject(fn line -> line == "" or String.starts_with?(line, "#") end)
        |> Enum.reject(&String.starts_with?(&1, "!"))
        |> Enum.uniq()

      {:error, _} ->
        []
    end
  end

  defp redundant_pattern?(pattern, covered) do
    trimmed = String.trim_trailing(pattern, "/")

    Enum.any?(covered, fn existing ->
      existing_trimmed = String.trim_trailing(existing, "/")

      pattern == existing or
        trimmed == existing_trimmed or
        String.ends_with?(existing, "/" <> pattern) or
        String.ends_with?(existing, "/" <> trimmed <> "/") or
        (String.starts_with?(existing, "**/") and
           String.trim_leading(existing, "**/") == pattern) or
        (String.starts_with?(existing, "**/") and
           String.trim_trailing(String.trim_leading(existing, "**/"), "/") == trimmed)
    end)
  end
end
